### ISSUE TITLE
Typo in Ch3, Gamma example

### ISSUE THREAD

**Issue by elb0** [proback/BYSH#13]
Hi folks, 

One of my students spotted that in Chapter 3, the section on gamma, there may be a small typo in the example. It is currently lines 447–449 in the [version on GitHub](https://github.com/proback/BeyondMLR/blob/master/03-Distribution-Theory.Rmd).

Suggest that:

```
\begin{align*}
P(Y < 3) = \int_0^3 \frac{2^4}{\Gamma(5)} y^{4} e^{-2y}dy = 0.715.
\end{align*}
```
should be:
```
\begin{align*}
P(Y < 3) = \int_0^3 \frac{2^5}{\Gamma(5)} y^{4} e^{-2y}dy = 0.715.
\end{align*}
```

Change is in the numerator, 2^4 -> 2^5, as _r_ is 5. 

<img width="582" alt="Screenshot 2021-03-02 at 12 36 00 PM" src="https://user-images.githubusercontent.com/22538970/109690065-f05c1280-7b53-11eb-9d2b-ba2415fe2b42.png">

**Comment by proback** [comment]
Thanks for catching this!  I will make this correction with my next batch of updates
