### ISSUE TITLE
Final chapter title becomes document title

### ISSUE THREAD

**Issue by napaxton** [proback/BYSH#14]
I have made the changes indicated in Issues [10](https://github.com/proback/BeyondMLR/issues/10), [11](https://github.com/proback/BeyondMLR/issues/11), [12](https://github.com/proback/BeyondMLR/issues/12), and [13](https://github.com/proback/BeyondMLR/issues/13).

Doing that, and making sure that I am using the latest (as of 23 April) version of `library(knitr)`, by entering `remotes::install_github('yihui/knitr')`, I get the following problem.

The title of the final chapter becomes the title of the document overall. Thus, the title of the document built from that repo isn't "Beyond Multiple Linear Regression" but instead "Chapter 11: Multilevel Generalized Linear Models."

I commented out the final chapter in `_bookdown.yml` (see below), with the result that Chapter 10's title became the overall document title:

~~~
book_filename: "bookdown-BeyondMLR"
chapter_name: "Chapter "
output_dir: docs
rmd_files: ["index.Rmd", 
  "01-Introduction.Rmd",
  "02-Beyond-Most-Least-Squares.Rmd",
  "03-Distribution-Theory.Rmd",
  "04-Poisson-Regression.Rmd",
  "05-Generalized-Linear-Models.Rmd",
  "06-Logistic-Regression.Rmd",
  "07-Correlated-Data.Rmd",
  "08-Introduction-to-Multilevel-Models.Rmd",
  "09-Two-Level-Longitudinal-Data.Rmd",
  "10-Multilevel-Data-With-More-Than-Two-Levels.Rmd",
  # "11-Generalized-Linear-Multilevel-Models.Rmd",
  "99-References.Rmd"]
clean: [packages.bib, bookdown.bbl]
~~~

A [commenter over at SO](https://stackoverflow.com/questions/67238264/bookdown-why-is-final-document-title-becoming-the-project-title) suggested that something in the index.Rmd could be causing this issue, but I could not find anything obvious…

**Comment by proback** [comment]
Hmm.  I wish I had an easy solution, but I didn't have this issue when originally knitting everything.  When I eventually make changes and updates and re-knit, I'll probably try to use quarto, which I've heard good things about.
