### ISSUE TITLE
Question/Suggestion for Chapter 4

### ISSUE THREAD

**Issue by datapumpernickel** [proback/BYSH#15]
Dear authors, 

I have found your book quite helpful in understanding some important aspects of Poisson regression - thank you so much for making this great resource available for free! 

I have a minor suggestions, which might be misguided both in content and place on github, please delete if that is the case. 

In chapter 4.4.3 Estimation and Inference you have the sentence: "or decreases by 0.5% (since 1−.995=.005)". This threw me aback when calculating my coefficients, because all of a sudden I got negative percentages, where I should see an increase. Hence, I started to look at other resources, Woolridge's Introductory Econometrics 5th Ed.: A Modern Approach (page 608) in particular and found, that it is more intuitive, if done the other way around: .995-1 = -.005. You will then get a negative percentage for a decrease and a positive percentage for an increase. 

I would love to learn more about it, in case I am wrong here. 

Thanks again for your work and all the best,
Paul

**Comment by proback** [comment]
I like this idea.  I'm going to TRY to make a set of changes this summer, and I'll plan to include this alternative way to think about percentage decreases.
