### ISSUE TITLE
Section 6.4.1 probability typo

### ISSUE THREAD

**Issue by ASKurz** [proback/BYSH#16]
In Section 6.4.1, we read:

> When the goalkeeper’s team is behind, the probability of a successful penalty kick is *p* = 22/24 or 0.833.

This is incorrect. The probability is .917.

```{r}
22 / 24
```

```{r}
[1] 0.9166667
```

**Comment by proback** [comment]
Thanks for catching this!  I'm going to TRY to get a set of changes made this summer, including this one.
